name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile -> make clean release
      run: make --trace clean release

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: WOPNPS2LD
        path: |
          WOPNPS2LD-*.ELF

    - name: Upload release artifact info
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: INFO
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md

  build-variants:
    strategy:
      fail-fast: false
      matrix:
        extra: [EXTRA_FEATURES=0, EXTRA_FEATURES=1]
        pademu: [PADEMU=0, PADEMU=1]
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Get version
      run: |
        echo "wOPL_VERSION=$(make woplversion)" >> $GITHUB_ENV

    - name: Compile -> make ${{ matrix.extra }} ${{ matrix.pademu }} ${{ matrix.extra }} NOT_PACKED=1
      run: |
        make --trace ${{ matrix.pademu }} ${{ matrix.extra }} NOT_PACKED=1
        mv wopl.elf WOPNPS2LD-${{ env.WOPL_VERSION }}-${{ matrix.pademu }}-${{ matrix.extra }}.ELF

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v4
      with:
        name: WOPNPS2LD-VARIANTS ${{ matrix.pademu }} ${{ matrix.extra }}
        path: WOPNPS2LD*.ELF

  merge-variants:
    runs-on: ubuntu-latest
    needs: build-variants
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: WOPNPS2LD-VARIANTS
          pattern: WOPNPS2LD-VARIANTS*
          delete-merged: true

  build-lang:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile -> make download_lng languages
      run: make --trace download_lng languages

    - name: Create artifact
      run: sh ./lng_pack.sh

    - name: Upload release artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: WOPNPS2LD-LANGS
        path: |
          WOPNPS2LD-LANGS-*.zip

  build-debug:
    strategy:
      fail-fast: false
      matrix:
        debug: [iopcore_debug, ingame_debug, eesio_debug, iopcore_ppctty_debug, ingame_ppctty_debug, DTL_T10000=1]
        # container_commit: [":main", "@sha256:1f00689809455d43b520e4cd4eea00c6be56d71819ae38efc6b55b56464cbd1e"] Replace with desired docker image hash or tag
        container_commit: [":main"]
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew${{ matrix.container_commit }}
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Get version
      run: |
        echo "WOPL_VERSION=$(make woplversion)" >> $GITHUB_ENV
        SHORT_COMMIT="${{ matrix.container_commit }}"
        # Extract the last 4 characters
        SHORT_COMMIT=${SHORT_COMMIT: -4}
        echo "SHORT_COMMIT=$SHORT_COMMIT" >> $GITHUB_ENV

    - name: Compile -> make debug
      run: |
        make ${{ matrix.debug }} --trace
        mv wopl.elf wopl-${{ matrix.debug }}-${{ env.WOPL_VERSION }}-${{ env.SHORT_COMMIT }}.elf

    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v4
      with:
        name: wopl-${{ matrix.debug }}-${{ env.WOPL_VERSION }}-${{ env.SHORT_COMMIT }}
        path: wopl-*.elf

  merge-debug:
    runs-on: ubuntu-latest
    needs: build-debug
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: WOPNPS2LD-DEBUG
          pattern: wopl-*
          delete-merged: true

  release:
    needs: [build, build-variants, build-lang]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: git fetch --prune --unshallow

    - name: Get version
      run: |
        echo "WOPL_VERSION=$(make woplversion)" >> $GITHUB_ENV

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Prepare artifacts for release
      run: |
        echo packing release of wOPL ${{ env.WOPL_VERSION }}
        cp INFO/* WOPNPS2LD/
        cp INFO/* WOPNPS2LD-VARIANTS/
        7z a -t7z WOPNPS2LD-${{ env.WOPL_VERSION }}.7z WOPNPS2LD/*
        7z a -t7z WOPNPS2LD-VARIANTS-${{ env.WOPL_VERSION }}.7z WOPNPS2LD-VARIANTS/*
        7z a -t7z WOPNPS2LD-LANGS-${{ env.WOPL_VERSION }}.7z WOPNPS2LD-LANGS/*
        cp -f WOPNPS2LD-${{ env.WOPL_VERSION }}.7z WOPNPS2LD.7z
        cp -f WOPNPS2LD-VARIANTS-${{ env.WOPL_VERSION }}.7z WOPNPS2LD-VARIANTS.7z
        cp -f WOPNPS2LD-LANGS-${{ env.WOPL_VERSION }}.7z WOPNPS2LD-LANGS.7z

    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "${{ steps.version.outputs.version }}"
        files: |
          WOPNPS2LD-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD-VARIANTS-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD-LANGS-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD.7z
          WOPNPS2LD-VARIANTS.7z
          WOPNPS2LD-LANGS.7z

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "${{ env.WOPL_VERSION }}"
        files: |
          WOPNPS2LD-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD-VARIANTS-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD-LANGS-${{ env.WOPL_VERSION }}.7z
          WOPNPS2LD.7z
          WOPNPS2LD-VARIANTS.7z
          WOPNPS2LD-LANGS.7z

    - name: Upload pre-release to Mega
      if: github.ref == 'refs/heads/master' && env.USERNAME != null
      uses: Difegue/action-megacmd@master
      with:
        args: put -c WOPNPS2LD.7z /WOPL/Pre-Release/${{ env.WOPL_VERSION }}/run_${{ github.run_number }}/

    - name: Upload release to Mega
      if: startsWith(github.ref, 'refs/tags/v') && env.USERNAME != null
      uses: Difegue/action-megacmd@master
      with:
        args: put -c WOPNPS2LD.7z /WOPL/Release/${{ env.WOPL_VERSION }}/
